# Generated by Django 5.0.3 on 2024-04-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eno', models.IntegerField()),
                ('ename', models.CharField(max_length=30)),
                ('eage', models.IntegerField()),
                ('esalary', models.FloatField()),
                ('edate_of_joining', models.DateField()),
                ('eadress', models.CharField(max_length=300)),
            ],
        ),
    ]
